package info.diit.entity;
// Generated Oct 31, 2016 1:41:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Companycategory generated by hbm2java
 */
public class Companycategory  implements java.io.Serializable {


     private String companyType;
     private Integer idct;
     private Set jobposts = new HashSet(0);

    public Companycategory() {
    }

	
    public Companycategory(String companyType) {
        this.companyType = companyType;
    }
    public Companycategory(String companyType, Integer idct, Set jobposts) {
       this.companyType = companyType;
       this.idct = idct;
       this.jobposts = jobposts;
    }
   
    public String getCompanyType() {
        return this.companyType;
    }
    
    public void setCompanyType(String companyType) {
        this.companyType = companyType;
    }
    public Integer getIdct() {
        return this.idct;
    }
    
    public void setIdct(Integer idct) {
        this.idct = idct;
    }
    public Set getJobposts() {
        return this.jobposts;
    }
    
    public void setJobposts(Set jobposts) {
        this.jobposts = jobposts;
    }




}


