package info.diit.entity;
// Generated Oct 31, 2016 1:41:14 PM by Hibernate Tools 4.3.1



/**
 * Companyreg generated by hbm2java
 */
public class Companyreg  implements java.io.Serializable {


     private Integer compId;
     private String compName;
     private String compUserName;
     private String compPhone;
     private String compEmail;
     private String compPassword;
     private String compType;
     private String compAddress;
     private String compDetail;
     private String compCon;

    public Companyreg() {
    }

    public Companyreg(String compName, String compUserName, String compPhone, String compEmail, String compPassword, String compType, String compAddress, String compDetail, String compCon) {
       this.compName = compName;
       this.compUserName = compUserName;
       this.compPhone = compPhone;
       this.compEmail = compEmail;
       this.compPassword = compPassword;
       this.compType = compType;
       this.compAddress = compAddress;
       this.compDetail = compDetail;
       this.compCon = compCon;
    }
   
    public Integer getCompId() {
        return this.compId;
    }
    
    public void setCompId(Integer compId) {
        this.compId = compId;
    }
    public String getCompName() {
        return this.compName;
    }
    
    public void setCompName(String compName) {
        this.compName = compName;
    }
    public String getCompUserName() {
        return this.compUserName;
    }
    
    public void setCompUserName(String compUserName) {
        this.compUserName = compUserName;
    }
    public String getCompPhone() {
        return this.compPhone;
    }
    
    public void setCompPhone(String compPhone) {
        this.compPhone = compPhone;
    }
    public String getCompEmail() {
        return this.compEmail;
    }
    
    public void setCompEmail(String compEmail) {
        this.compEmail = compEmail;
    }
    public String getCompPassword() {
        return this.compPassword;
    }
    
    public void setCompPassword(String compPassword) {
        this.compPassword = compPassword;
    }
    public String getCompType() {
        return this.compType;
    }
    
    public void setCompType(String compType) {
        this.compType = compType;
    }
    public String getCompAddress() {
        return this.compAddress;
    }
    
    public void setCompAddress(String compAddress) {
        this.compAddress = compAddress;
    }
    public String getCompDetail() {
        return this.compDetail;
    }
    
    public void setCompDetail(String compDetail) {
        this.compDetail = compDetail;
    }
    public String getCompCon() {
        return this.compCon;
    }
    
    public void setCompCon(String compCon) {
        this.compCon = compCon;
    }




}


