package info.diit.entity;
// Generated Oct 31, 2016 1:41:14 PM by Hibernate Tools 4.3.1



/**
 * Experience generated by hbm2java
 */
public class Experience  implements java.io.Serializable {


     private Integer expId;
     private Jobseekerreg jobseekerreg;
     private String companyName;
     private String position;
     private String location;
     private String department;
     private String duration;
     private String responsibilty;
     private String from;
     private String to;

    public Experience() {
    }

    public Experience(Jobseekerreg jobseekerreg, String companyName, String position, String location, String department, String duration, String responsibilty, String from, String to) {
       this.jobseekerreg = jobseekerreg;
       this.companyName = companyName;
       this.position = position;
       this.location = location;
       this.department = department;
       this.duration = duration;
       this.responsibilty = responsibilty;
       this.from = from;
       this.to = to;
    }
   
    public Integer getExpId() {
        return this.expId;
    }
    
    public void setExpId(Integer expId) {
        this.expId = expId;
    }
    public Jobseekerreg getJobseekerreg() {
        return this.jobseekerreg;
    }
    
    public void setJobseekerreg(Jobseekerreg jobseekerreg) {
        this.jobseekerreg = jobseekerreg;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public String getDuration() {
        return this.duration;
    }
    
    public void setDuration(String duration) {
        this.duration = duration;
    }
    public String getResponsibilty() {
        return this.responsibilty;
    }
    
    public void setResponsibilty(String responsibilty) {
        this.responsibilty = responsibilty;
    }
    public String getFrom() {
        return this.from;
    }
    
    public void setFrom(String from) {
        this.from = from;
    }
    public String getTo() {
        return this.to;
    }
    
    public void setTo(String to) {
        this.to = to;
    }




}


