package info.diit.entity;
// Generated Oct 31, 2016 1:41:14 PM by Hibernate Tools 4.3.1



/**
 * Reference generated by hbm2java
 */
public class Reference  implements java.io.Serializable {


     private Integer refId;
     private Jobseekerreg jobseekerreg;
     private String name;
     private String orgName;
     private String designation;
     private String contactNo;
     private String email;
     private String relation;
     private String name2;
     private String orgName2;
     private String designation2;
     private String contactNo2;
     private String email2;
     private String relation2;

    public Reference() {
    }

    public Reference(Jobseekerreg jobseekerreg, String name, String orgName, String designation, String contactNo, String email, String relation, String name2, String orgName2, String designation2, String contactNo2, String email2, String relation2) {
       this.jobseekerreg = jobseekerreg;
       this.name = name;
       this.orgName = orgName;
       this.designation = designation;
       this.contactNo = contactNo;
       this.email = email;
       this.relation = relation;
       this.name2 = name2;
       this.orgName2 = orgName2;
       this.designation2 = designation2;
       this.contactNo2 = contactNo2;
       this.email2 = email2;
       this.relation2 = relation2;
    }
   
    public Integer getRefId() {
        return this.refId;
    }
    
    public void setRefId(Integer refId) {
        this.refId = refId;
    }
    public Jobseekerreg getJobseekerreg() {
        return this.jobseekerreg;
    }
    
    public void setJobseekerreg(Jobseekerreg jobseekerreg) {
        this.jobseekerreg = jobseekerreg;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getOrgName() {
        return this.orgName;
    }
    
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getRelation() {
        return this.relation;
    }
    
    public void setRelation(String relation) {
        this.relation = relation;
    }
    public String getName2() {
        return this.name2;
    }
    
    public void setName2(String name2) {
        this.name2 = name2;
    }
    public String getOrgName2() {
        return this.orgName2;
    }
    
    public void setOrgName2(String orgName2) {
        this.orgName2 = orgName2;
    }
    public String getDesignation2() {
        return this.designation2;
    }
    
    public void setDesignation2(String designation2) {
        this.designation2 = designation2;
    }
    public String getContactNo2() {
        return this.contactNo2;
    }
    
    public void setContactNo2(String contactNo2) {
        this.contactNo2 = contactNo2;
    }
    public String getEmail2() {
        return this.email2;
    }
    
    public void setEmail2(String email2) {
        this.email2 = email2;
    }
    public String getRelation2() {
        return this.relation2;
    }
    
    public void setRelation2(String relation2) {
        this.relation2 = relation2;
    }




}


