package info.diit.entity;
// Generated Oct 31, 2016 1:41:14 PM by Hibernate Tools 4.3.1



/**
 * Training generated by hbm2java
 */
public class Training  implements java.io.Serializable {


     private Integer trainingId;
     private Jobseekerreg jobseekerreg;
     private String trainingTitle;
     private String topic;
     private String duration;
     private String institute;
     private String location;
     private String trainingYear;
     private String trainingTitle2;
     private String topic2;
     private String duration2;
     private String institute2;
     private String location2;
     private String trainingYear2;

    public Training() {
    }

    public Training(Jobseekerreg jobseekerreg, String trainingTitle, String topic, String duration, String institute, String location, String trainingYear, String trainingTitle2, String topic2, String duration2, String institute2, String location2, String trainingYear2) {
       this.jobseekerreg = jobseekerreg;
       this.trainingTitle = trainingTitle;
       this.topic = topic;
       this.duration = duration;
       this.institute = institute;
       this.location = location;
       this.trainingYear = trainingYear;
       this.trainingTitle2 = trainingTitle2;
       this.topic2 = topic2;
       this.duration2 = duration2;
       this.institute2 = institute2;
       this.location2 = location2;
       this.trainingYear2 = trainingYear2;
    }
   
    public Integer getTrainingId() {
        return this.trainingId;
    }
    
    public void setTrainingId(Integer trainingId) {
        this.trainingId = trainingId;
    }
    public Jobseekerreg getJobseekerreg() {
        return this.jobseekerreg;
    }
    
    public void setJobseekerreg(Jobseekerreg jobseekerreg) {
        this.jobseekerreg = jobseekerreg;
    }
    public String getTrainingTitle() {
        return this.trainingTitle;
    }
    
    public void setTrainingTitle(String trainingTitle) {
        this.trainingTitle = trainingTitle;
    }
    public String getTopic() {
        return this.topic;
    }
    
    public void setTopic(String topic) {
        this.topic = topic;
    }
    public String getDuration() {
        return this.duration;
    }
    
    public void setDuration(String duration) {
        this.duration = duration;
    }
    public String getInstitute() {
        return this.institute;
    }
    
    public void setInstitute(String institute) {
        this.institute = institute;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getTrainingYear() {
        return this.trainingYear;
    }
    
    public void setTrainingYear(String trainingYear) {
        this.trainingYear = trainingYear;
    }
    public String getTrainingTitle2() {
        return this.trainingTitle2;
    }
    
    public void setTrainingTitle2(String trainingTitle2) {
        this.trainingTitle2 = trainingTitle2;
    }
    public String getTopic2() {
        return this.topic2;
    }
    
    public void setTopic2(String topic2) {
        this.topic2 = topic2;
    }
    public String getDuration2() {
        return this.duration2;
    }
    
    public void setDuration2(String duration2) {
        this.duration2 = duration2;
    }
    public String getInstitute2() {
        return this.institute2;
    }
    
    public void setInstitute2(String institute2) {
        this.institute2 = institute2;
    }
    public String getLocation2() {
        return this.location2;
    }
    
    public void setLocation2(String location2) {
        this.location2 = location2;
    }
    public String getTrainingYear2() {
        return this.trainingYear2;
    }
    
    public void setTrainingYear2(String trainingYear2) {
        this.trainingYear2 = trainingYear2;
    }




}


