package info.diit.entity;
// Generated Oct 31, 2016 1:41:14 PM by Hibernate Tools 4.3.1



/**
 * UploadImage generated by hbm2java
 */
public class UploadImage  implements java.io.Serializable {


     private Integer imageId;
     private String imageName;
     private byte[] image;

    public UploadImage() {
    }

    public UploadImage(String imageName, byte[] image) {
       this.imageName = imageName;
       this.image = image;
    }
   
    public Integer getImageId() {
        return this.imageId;
    }
    
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }
    public String getImageName() {
        return this.imageName;
    }
    
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }




}


