package info.diit.entity;
// Generated Oct 31, 2016 1:41:14 PM by Hibernate Tools 4.3.1



/**
 * Userroles generated by hbm2java
 */
public class Userroles  implements java.io.Serializable {


     private int jsId;
     private Integer compId;
     private Integer roleId;

    public Userroles() {
    }

	
    public Userroles(int jsId) {
        this.jsId = jsId;
    }
    public Userroles(int jsId, Integer compId, Integer roleId) {
       this.jsId = jsId;
       this.compId = compId;
       this.roleId = roleId;
    }
   
    public int getJsId() {
        return this.jsId;
    }
    
    public void setJsId(int jsId) {
        this.jsId = jsId;
    }
    public Integer getCompId() {
        return this.compId;
    }
    
    public void setCompId(Integer compId) {
        this.compId = compId;
    }
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }




}


